### ISSUE TITLE
是在这里提问题么？

### ISSUE THREAD

**Issue by ferocknew** [walkor/workerman-thrift#1]
try {
    $client = ThriftClient::instance('HelloWorld');
} catch(Exception $e) {
    exit($e -> getMessage());
}

但是抓取不到异常的服务器（连不上）报错

**Comment by 3032441712** [comment]
exception Xception {
  1: i32 code,
  2: string message
}
异常定义成这样的,也就是 code message 这样才能用$e->getCode()与$e->getMessage()获取到异常.
