### ISSUE TITLE
批量调用失败

### ISSUE THREAD

**Issue by longfeiwan1566** [walkor/workerman-thrift#4]
有一个问题，采用workman的php做thrift服务端，java客户端，批量调用测试的时候为啥每次都得open一下，否则直接死了，也没有任何异常信息，但是貌似php直接调用时ok的。

**Comment by walkor** [comment]
workman的php做thrift服务端是短链接，每次调用要重新建立链接

**Comment by longfeiwan1566** [comment]
好的 谢谢

**Comment by btcnash** [comment]
请问为什么不支持长连接呢？

**Comment by walkor** [comment]
这个是thrift的php库决定的，php的thrift库本身就不支持长链接。
当然我也没非常深入的研究
