### ISSUE TITLE
请问可以配置用户密码连接吗？

### ISSUE THREAD

**Issue by smileymrking** [walkor/workerman-thrift#9]
我翻看了一下源码，没有找到相关配置的代码，请问有相关的配置吗，如果没有那是否表示别人得到了rpc服务器的IP和端口就可以进行连接了？有没有相应的安全验证呢？刚接触thrift不久望解答，谢谢！

**Comment by walkor** [comment]
rpc一般都是提供内网调用的。
如果需要外网调用，可以自己想办法加验证逻辑。

**Comment by smileymrking** [comment]
明白了，谢谢！
